trangtest:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "localhost"
      port: 5433
      user: upstream
      password: "password"
      database: postgres
      schema: test
      threads: 1